Vagrant.configure('2') do |config|
  config.vm.box = 'azure'
  config.ssh.private_key_path = "~/.ssh/id_rsa"
  config.vm.provider :azure do |azure, override|

    # each of the below values will default to use the env vars named as below if not specified explicitly
    azure.tenant_id = '5cf7310e-091a-4bc5-acd7-26c721d4cccd'
    azure.client_id = '8dd03566-6d7a-4210-9cd7-5dd2380e11f1'
    azure.client_secret = 'ADU0Mm82OIkoT_5-76HWR6vaBTD3W63XLd'
    azure.subscription_id = '8520c26f-0ff2-45cc-8d11-d79173d6a516'
    # onderstaand zijn specifieke vm properties
    azure.resource_group_name='projectenTest2'
#    azure.vm_name="eersteMachine"
    azure.vm_image_urn = 'OpenLogic:CentOS:7.5:latest'
    azure.instance_ready_timeout = 600
    azure.vm_password = 'umoeder'
    azure.admin_username = "santi"
  #  override.winrm.transport = :ssl
  #  override.winrm.port = 5986
  #  override.winrm.ssl_peer_verification = false # must be false if using a self signed cert
  end

end
